name: update-funds

on:
  # every 10th of the month at 07:00 Israel (04:00 UTC)
  schedule:
    - cron: '0 4 10 * *'
  workflow_dispatch:        # allows manual run in Actions tab

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Build funds.json
        run: |
          python fetch_funds.py

      - name: Commit and push funds.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add funds.json
          git commit -m "auto: update $(date -u '+%F')" || echo "No changes"
          git push
